theme: jekyll-theme-slate
title: Tristan Williams
author: Tristan Williams
description: PhD Researcher in Remote Sensing at Universitat de Valencia, European Space Agency and University of Leipzig.
picture: ![image](https://user-images.githubusercontent.com/98157176/156783283-4d4ee691-2aba-4a39-816e-90558342ef7d.png)

nav-bar links:
  About Me: ""
  Code: 
  Posts:
 
social-network-links:
  email: Tristan.Williams@esa.int
  github: https://github.com/tristaneo
  Linkedin: https://it.linkedin.com/in/tristan-williams-440143180
  Twitter: https://twitter.com/Tristan_Earth
  google-scholar: https://scholar.google.com/citations?user=yoNnOcMAAAAJ&hl=en&oi=ao
  
 
