theme: jekyll-theme-slate
title: Tristan Williams
description: PhD Researcher in Remote Sensing at University of Valencia & European Space Agency. This page follows my research into terrestrial ecosystems, and the methods and code that I use to analyse them.
