theme: jekyll-theme-slate
title: Tristan Williams
author: Tristan Williams

# Plugins
plugins:
  - jekyll-feed # Generate an RSS feed for your site
  - jekyll-sitemap # Generate a sitemap for your site
  - jekyll-seo-tag # Generate SEO-related meta tags

# Navigation
nav:
  - title: Home
    url: /
  - title: Research
    url: /research

# Social media links
social:
  - title: Twitter
    url: https://twitter.com/tristankew
  - title: GitHub
    url: https://github.com/tristaneo

# Build configuration
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor


# nav-bar links:
#   About Me: ""
#   Projects: ""
#   Code: ""
#   Papers: "" 
#avatar: "![moustache](https://user-images.githubusercontent.com/98157176/156788671-b99523ad-0d86-4ff1-9bf7-b920422594db.jpg)"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
#round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
# title-img: ![moustache](https://user-images.githubusercontent.com/98157176/156788671-b99523ad-0d86-4ff1-9bf7-b920422594db.jpg)
 
#social-network-links:
 # email: Tristan.Williams@esa.int
  #github: https://github.com/tristaneo
  #Linkedin: https://it.linkedin.com/in/tristan-williams-440143180
  #Twitter: https://twitter.com/Tristan_Earth
  #google-scholar: https://scholar.google.com/citations?user=yoNnOcMAAAAJ&hl=en&oi=ao
