theme: jekyll-theme-slate
title: Tristan Williams
description: PhD Researcher in Remote Sensing at University of Valencia & European Space Agency. This blog follows my research into terrestrial ecosystems, and the methods that I use to analyse them.
