theme: jekyll-theme-slate
title: Tristan Williams
description: PhD Researcher in Remote Sensing at Universitat de Valencia, European Space Agency and University of Leipzig.
picture: ![image](https://user-images.githubusercontent.com/98157176/156783283-4d4ee691-2aba-4a39-816e-90558342ef7d.png)
